### PR TITLE
Pynoddy

### PR DESCRIPTION
**Pull request by danielsk78**
Add pynoddy to sandbox modules

### CODE REVIEW

**Comment by flohorovicic** [comment]
Hi @danielsk78 , just a quick question: is this pull request still up to date? Happy to merge - just wanted to check as you did some recent changes...

**Comment by danielsk78** [comment]
Hi @flohorovicic, the branch was ready to merge. However, would be good to test it with the latest changes to check if it is still compatible.

**Comment by flohorovicic** [comment]
@danielsk78 as we are just at pull requests... this one is also still open :-) any update from your side?

**Comment by danielsk78** [comment]
Sorry for the delay. I'm testing the package if everything is still compatible. 
The tricky thing is installing pynoddy. The rest is working how it should be.

**Comment by danielsk78** [comment]
Pynoddy model displayed in dummy sensor
image

**Pull request merged**
